version: 0.2

phases:
  pre_build:
    commands:
      - echo [PRE_BUILD] 퍼블릭 ECR 로그인
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q9c7w1n2

  build:
    commands:
      - echo [BUILD] Maven 빌드 수행
      - mvn clean package
      - echo [BUILD] Docker 이미지 빌드
      - docker build -t hwtesta .

  post_build:
    commands:
      - echo [POST_BUILD] 태깅 및 푸시
      - docker tag hwtesta:latest public.ecr.aws/q9c7w1n2/hwtesta:latest
      - docker push public.ecr.aws/q9c7w1n2/hwtesta:latest